# 'brew install'
brew "htop"
brew "ripgrep"
brew "bat"
brew "eza"
brew "starship"
brew "fzf"
brew "zsh-autosuggestions"
brew "atuin"
brew "fd"
brew "tmux"
brew "neovim"
brew "watchexec"
brew "zoxide"
brew "hyperfine"
# brew "helix"
brew "gh"
# brew "restic"
brew "duckdb"
brew "rclone"
brew "jq"
brew "gping"
brew "gitui"
brew "csvlens"
brew "mise"

# GIS
brew "tippecanoe"
brew "osmium-tool"

cask "macfuse"

# tap "1password/tap"
# tap "clojure/tools"
# tap "ekzhang/bore"
# tap "homebrew/bundle"
# tap "mongodb/brew"
# tap "nats-io/nats-tools"
# tap "noborus/tap"
# tap "ory/tap"
# tap "oven-sh/bun"
# tap "rs/tap"
# tap "sidneys/homebrew"
# tap "static-web-server/static-web-server"
# tap "urbica/tap"
# brew "rs/tap/curlie"
# brew "tree"
# brew "node"
# brew "lsd"
# brew "glow"
# brew "go"
# brew "just"
# brew "lua"
# brew "pipx"
# brew "qemu"
# brew "redis"
# brew "telnet"
# brew "tmux"
# brew "wget"
# brew "zellij"
# brew "deno"
# brew "aria2"
# brew "bottom"
# brew "duckdb"
# brew "dust"
# brew "awscli"
# brew "tesseract"
# brew "ffmpeg"
# brew "bandwhich"
# brew "rapidjson"
# brew "cabextract"
# brew "pkg-config"
# brew "direnv"
# brew "elixir"
# brew "opus"
# brew "libheif"
# brew "libspatialite"
# brew "netcdf"
# brew "nss"
# brew "numpy", link: false
# brew "poppler"
# brew "gdal"
# brew "ghc"
# brew "oven-sh/bun/bun"
# brew "gitui"
# brew "go-task"
# brew "golang-migrate"
# brew "grpc@1.54"
# brew "h3"
# brew "hexyl"
# brew "jpeg"
# brew "librdkafka"
# brew "kcat"
# brew "kompose"
# brew "openjdk"
# brew "kotlin"
# brew "kubernetes-cli"
# brew "lazygit"
# brew "libxmlsec1"
# brew "lua-language-server"
# brew "luajit"
# brew "luv"
# brew "marksman"
# brew "maven"
# brew "minikube"
# brew "mkcert"
# brew "nats-server"
# brew "tree-sitter"
# brew "nim"
# brew "oath-toolkit"
# brew "opam"
# brew "postgresql@14"
# brew "procs"
# brew "sd"
# brew "sftpgo"
# brew "shapelib"
# brew "taplo"
# brew "tokei"
# brew "wimlib"
# brew "clojure/tools/clojure"
# brew "ekzhang/bore/bore"
# brew "mongodb/brew/mongodb-database-tools"
# brew "nats-io/nats-tools/nats"
# brew "noborus/tap/ov"
# brew "ory/tap/cli"
# brew "ory/tap/keto"
# brew "ory/tap/kratos"
# brew "zig"

# cask "1password-cli"

# vscode "42Crunch.vscode-openapi"
# vscode "ahmadalli.vscode-nginx-conf"
# vscode "ahmadawais.shades-of-purple"
# vscode "arcticicestudio.nord-visual-studio-code"
# vscode "asvetliakov.vscode-neovim"
# vscode "blanu.vscode-styled-jsx"
# vscode "bradlc.vscode-tailwindcss"
# vscode "buster.ndjson-colorizer"
# vscode "DanielSanMedium.dscodegpt"
# vscode "davidbwaters.macos-modern-theme"
# vscode "dbaeumer.vscode-eslint"
# vscode "denoland.vscode-deno"
# vscode "DotJoshJohnson.xml"
# vscode "eamodio.gitlens"
# vscode "esbenp.prettier-vscode"
# vscode "ginfuru.ginfuru-onedark-raincoat-theme"
# vscode "GitHub.copilot"
# vscode "GitHub.vscode-pull-request-github"
# vscode "golang.go"
# vscode "googlecloudtools.cloudcode"
# vscode "GrapeCity.gc-excelviewer"
# vscode "hangxingliu.vscode-nginx-conf-hint"
# vscode "jumpinjackie.vscode-map-preview"
# vscode "mathiasfrohlich.Kotlin"
# vscode "matt-meyers.vscode-dbml"
# vscode "max-SS.Cyberpunk"
# vscode "mikestead.dotenv"
# vscode "mongodb.mongodb-vscode"
# vscode "monokai.theme-monokai-pro-vscode"
# vscode "mrmlnc.vscode-json5"
# vscode "ms-azuretools.vscode-docker"
# vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
# vscode "ms-ossdata.vscode-postgresql"
# vscode "ms-python.isort"
# vscode "ms-python.python"
# vscode "ms-python.vscode-pylance"
# vscode "ms-toolsai.jupyter"
# vscode "ms-toolsai.jupyter-keymap"
# vscode "ms-toolsai.jupyter-renderers"
# vscode "ms-toolsai.vscode-jupyter-cell-tags"
# vscode "ms-toolsai.vscode-jupyter-slideshow"
# vscode "ms-vscode-remote.remote-containers"
# vscode "ms-vscode-remote.remote-ssh"
# vscode "ms-vscode-remote.remote-ssh-edit"
# vscode "ms-vscode-remote.vscode-remote-extensionpack"
# vscode "ms-vscode.hexeditor"
# vscode "ms-vscode.makefile-tools"
# vscode "ms-vscode.remote-explorer"
# vscode "ms-vscode.remote-server"
# vscode "ms-vsliveshare.vsliveshare"
# vscode "mtxr.sqltools"
# vscode "mtxr.sqltools-driver-pg"
# vscode "mtxr.sqltools-driver-sqlite"
# vscode "octref.vetur"
# vscode "Prisma.prisma"
# vscode "rangav.vscode-thunder-client"
# vscode "raynigon.nginx-formatter"
# vscode "redhat.java"
# vscode "redhat.vscode-commons"
# vscode "redhat.vscode-yaml"
# vscode "RobbOwen.synthwave-vscode"
# vscode "rome.rome"
# vscode "rust-lang.rust-analyzer"
# vscode "shanoor.vscode-nginx"
# vscode "slevesque.shader"
# vscode "svelte.svelte-vscode"
# vscode "tamasfe.even-better-toml"
# vscode "tauri-apps.tauri-vscode"
# vscode "teabyii.ayu"
# vscode "tomphilbin.gruvbox-themes"
# vscode "unifiedjs.vscode-mdx"
# vscode "VisualStudioExptTeam.intellicode-api-usage-examples"
# vscode "VisualStudioExptTeam.vscodeintellicode"
# vscode "vscjava.vscode-java-debug"
# vscode "vscjava.vscode-java-dependency"
# vscode "vscjava.vscode-java-pack"
# vscode "vscjava.vscode-java-test"
# vscode "vscjava.vscode-maven"
# vscode "vscodevim.vim"
# vscode "william-voyek.vscode-nginx"
# vscode "withfig.fig"
# vscode "xaver.clang-format"
# vscode "zhuangtongfa.material-theme"
