theme = "rose-pine"

[editor]
line-number = "relative"
mouse = true
scrolloff = 5
cursorline = true
cursorcolumn = false
bufferline = "always"
true-color = true
color-modes = true  
# auto-pairs = true # defaults to `true`

idle-timeout = 0
auto-format = true
auto-completion = true
completion-trigger-len = 2
 
[editor.cursor-shape]
insert = "underline" # bar
normal = "block"
select = "block"

[editor.file-picker]
hidden = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true #	Display LSP progress messages below statusline1
auto-signature-help = true #	Enable automatic popup of signature help (parameter hints)	true
display-signature-help-docs = true #
 